/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Patients;

import Doctors.connect;
import Login.loginPage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author GaXown
 */
public class addPatient extends javax.swing.JFrame {
    DefaultTableModel deftmod = new DefaultTableModel();
    /**
     * Creates new form addPatient
     */
    public addPatient() {
        initComponents();
        Object columns[] = {"id","name","age","gender","address","phone_number","disease"};
        deftmod.setColumnIdentifiers(columns);
        DoctorsTable.setModel(deftmod);
        try {
            loadData();
        } catch (ClassNotFoundException ex) {
            System.out.println("class not found error");
        } catch (SQLException ex) {
            System.out.println("sql error");
        }
        
    }

    public void loadData() throws ClassNotFoundException, SQLException {
       Class.forName("com.mysql.jdbc.Driver");
   
         
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitaldb","root","");
        deftmod.getDataVector().removeAllElements();
        deftmod.fireTableDataChanged();
        String querry = "select * from patient_info";
        
    
        try {
            java.sql.Statement s = con.createStatement();
           ResultSet rs = s.executeQuery(querry);
            Object columnData[] = new Object[8];
            while (rs.next()) {
               
                columnData[0] = rs.getString("id");
                columnData[1] = rs.getString("name");
                columnData[2] = rs.getInt("age");
                columnData[3] = rs.getString("gender");
                columnData[4] = rs.getString("address");
                columnData[5] = rs.getString("phone");
                columnData[6] = rs.getString("disease");
               
                deftmod.addRow(columnData);

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        logOut_Btn2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        p_id = new textfield.TextField();
        p_age = new textfield.PasswordField();
        p_name = new textfield.TextField();
        p_gender = new textfield.TextField();
        p_date = new textfield.TextField();
        p_disease = new textfield.TextField();
        p_adresse = new textfield.TextField();
        p_phone = new textfield.TextField();
        jLabel2 = new javax.swing.JLabel();
        p_add_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DoctorsTable.setAutoCreateRowSorter(true);
        DoctorsTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DoctorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Patient Phone", "Patient Adress", "Patient Disease", "Patient Gender", "Patient Age", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DoctorsTable.setGridColor(new java.awt.Color(204, 204, 204));
        DoctorsTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(DoctorsTable);

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Add A patient__________ ");

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backs.png"))); // NOI18N
        back_btn.setText("jLabel2");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        logOut_Btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross.png"))); // NOI18N
        logOut_Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut_Btn2logOut_BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOut_Btn2)
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logOut_Btn2)
                            .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_id.setLabelText("ID");
        p_id.setName("ID"); // NOI18N
        jPanel3.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        p_age.setLabelText("Age");
        jPanel3.add(p_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        p_name.setLabelText("Username");
        jPanel3.add(p_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 170, -1));

        p_gender.setLabelText("Gender");
        jPanel3.add(p_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, -1));

        p_date.setLabelText("Date");
        jPanel3.add(p_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 260, -1));

        p_disease.setLabelText("Disease");
        jPanel3.add(p_disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 260, -1));

        p_adresse.setLabelText("Adress");
        jPanel3.add(p_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 260, -1));

        p_phone.setLabelText("Phone number");
        jPanel3.add(p_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 260, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Humaaans - 3 Characters.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 390, 230));

        p_add_btn.setBackground(new java.awt.Color(255, 255, 255));
        p_add_btn.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        p_add_btn.setForeground(new java.awt.Color(108, 99, 255));
        p_add_btn.setText("ADD");
        p_add_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 99, 255), 2, true));
        p_add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_add_btnActionPerformed(evt);
            }
        });
        jPanel3.add(p_add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 250, 170, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        new PatientsCP().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    private void p_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_add_btnActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            String id = p_id.getText();
            String name = p_name.getText();
            String address = p_adresse.getText();
            String phone = p_phone.getText();
            String disease = p_disease.getText();
            String gender = p_gender.getText();
            String date = p_date.getText();
            int age = Integer.parseInt(p_age.getText());
            
            
            Connection con = null;
            con = connect.connectdb();
            String querry = "insert into patient_info values(?,?,?,?,?,?,?,?)";
            java.sql.PreparedStatement st = con.prepareStatement(querry);
            st.setString(1, date);
            st.setString(2, id);
            st.setString(3, name);
            st.setInt(4, age);
            st.setString(5, gender);
            st.setString(6, address);
            st.setString(7, phone);
            st.setString(8, disease);
            int x = st.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(null, "Data Saved ("  + x + " row updated)");   
        } catch (ClassNotFoundException ex) {
            System.out.println("errorrrr");
        } catch (SQLException ex) {
            System.out.println("error2");        
        }
    }//GEN-LAST:event_p_add_btnActionPerformed

    private void logOut_Btn2logOut_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut_Btn2logOut_BtnMouseClicked
        new loginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_Btn2logOut_BtnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DoctorsTable;
    private javax.swing.JLabel back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOut_Btn2;
    private javax.swing.JButton p_add_btn;
    private textfield.TextField p_adresse;
    private textfield.PasswordField p_age;
    private textfield.TextField p_date;
    private textfield.TextField p_disease;
    private textfield.TextField p_gender;
    private textfield.TextField p_id;
    private textfield.TextField p_name;
    private textfield.TextField p_phone;
    // End of variables declaration//GEN-END:variables
}
