/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Patients;

import Login.loginPage;
import Doctors.connect;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GaXown
 */
public class updatePatient extends javax.swing.JFrame {
DefaultTableModel deftmod = new DefaultTableModel();
    
    String count;
    String date;
    String id;
    String name;
    int age;
    String gender;
    String address;
    String phone;
    String disease;
    
    /**
     * Creates new form SearchTable
     */
    public updatePatient() {
        initComponents();
         Object columns[] = {"date","id","name","age","gender","address","phone_number","disease"};
        deftmod.setColumnIdentifiers(columns);
        DoctorsTable.setModel(deftmod);
        try {
            loadData();
        } catch (ClassNotFoundException ex) {
            System.out.println("class not found error");
        } catch (SQLException ex) {
            System.out.println("load sql error");
        }
    }

    public void loadData() throws ClassNotFoundException, SQLException {
       Class.forName("com.mysql.jdbc.Driver");
   
         
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitaldb","root","");
        deftmod.getDataVector().removeAllElements();
        deftmod.fireTableDataChanged();
        String querry = "select * from patient_info";
        
    
        try {
            java.sql.Statement s = con.createStatement();
           ResultSet rs = s.executeQuery(querry);
            Object columnData[] = new Object[8];
            while (rs.next()) {
                columnData[0] = rs.getString("date");
                columnData[1] = rs.getString("id");
                columnData[2] = rs.getString("name");
                columnData[3] = rs.getInt("age");
                columnData[4] = rs.getString("gender");
                columnData[5] = rs.getString("address");
                columnData[6] = rs.getString("phone");
                columnData[7] = rs.getString("disease");
               
                deftmod.addRow(columnData);

            }
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        logOut_Btn2 = new javax.swing.JLabel();
        p_id = new textfield.TextField();
        p_update_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DoctorsTable.setAutoCreateRowSorter(true);
        DoctorsTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DoctorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Patient Phone", "Patient Adress", "Patient Disease", "Patient Gender", "Patient Age", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DoctorsTable.setGridColor(new java.awt.Color(204, 204, 204));
        DoctorsTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        DoctorsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DoctorsTable);

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Update Patient ________");

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backs.png"))); // NOI18N
        back_btn.setText("jLabel2");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        logOut_Btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross.png"))); // NOI18N
        logOut_Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut_Btn2logOut_BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOut_Btn2)
                .addGap(217, 217, 217)
                .addComponent(jLabel1)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOut_Btn2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        p_id.setLabelText("ID");
        p_id.setName("ID"); // NOI18N

        p_update_btn.setBackground(new java.awt.Color(255, 255, 255));
        p_update_btn.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        p_update_btn.setForeground(new java.awt.Color(108, 99, 255));
        p_update_btn.setText("UPDATE");
        p_update_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 99, 255), 2, true));
        p_update_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_update_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(p_id, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p_update_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(387, 387, 387))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(p_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        new PatientsCP().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    private void DoctorsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorsTableMouseClicked
        // TODO add your handling code here:
        int row = DoctorsTable.getSelectedRow();
        
    
    date = DoctorsTable.getValueAt(row, 0).toString();
    id = DoctorsTable.getValueAt(row, 1).toString();
    name = DoctorsTable.getValueAt(row, 2).toString();
    age = Integer.parseInt(DoctorsTable.getValueAt(row, 3).toString()) ;
    gender= DoctorsTable.getValueAt(row, 4).toString();
    address= DoctorsTable.getValueAt(row, 5).toString();
    phone  = DoctorsTable.getValueAt(row, 6).toString();
    disease= DoctorsTable.getValueAt(row, 7).toString();
    }//GEN-LAST:event_DoctorsTableMouseClicked

    private void p_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_update_btnActionPerformed
        // TODO add your handling code here:
        try {
        // TODO add your handling code here:
        count = p_id.getText();
        String querry = "update patient_info set date ='"+date+"',id='"+id+"',name='"+name+"',age='"+age+"',gender='"+gender+"',address='"+address+"',phone='"+phone+"',disease='"+disease+"' where id = '"+count+"';";
        Connection conn;
        conn = connect.connectdb();
        java.sql.PreparedStatement ps = conn.prepareStatement(querry);
        deftmod.getDataVector().removeAllElements();
        deftmod.fireTableDataChanged();
        ps.execute();
        loadData();
        JOptionPane.showMessageDialog(null, "Data Saved");
        conn.close();
        
    } catch (ClassNotFoundException ex) {
        System.out.println("class error");
    } catch (SQLException ex) {
        System.out.println(" update sql error");
    }
    }//GEN-LAST:event_p_update_btnActionPerformed

    private void logOut_Btn2logOut_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut_Btn2logOut_BtnMouseClicked
        new loginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_Btn2logOut_BtnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DoctorsTable;
    private javax.swing.JLabel back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOut_Btn2;
    private textfield.TextField p_id;
    private javax.swing.JButton p_update_btn;
    // End of variables declaration//GEN-END:variables
}
