/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.awt.SplashScreen;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author GaXown
 */
public class loadingPage extends javax.swing.JFrame {

    /**
     * Creates new form loadingPage
     */
    public loadingPage() {
        initComponents();
    }

    public static void launch() throws ClassNotFoundException, SQLException{
        loadingPage start = new loadingPage();
        start.setVisible(true);
        try {
            for (int i=0; i<=100; i++) {
                Thread.sleep(100);
                start.loadingValue.setText(i + "%");
                if (i == 10){
                    start.loadingLabel.setText("Setting Modules On ...");
                } else if (i >= 38 && i <= 45) {
                    start.loadingLabel.setText("establishing Database Connection ...");
                    Thread.sleep(600);
                } else if (i >= 60 && i <= 67) {
                    Thread.sleep(600);
                    start.loadingLabel.setText("Fetching DATA ...");
                } else if (i >= 96 && i <= 99) {
                    Thread.sleep(800);
                    start.loadingLabel.setText("Launching Application ...");
                }
                start.progressBar.setValue(i);
                if (i == 100) {
                    Thread.sleep(300);
                }
            } 
            start.setVisible(false);
            new loginPage().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        loadingValue = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hospital.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 0, 640, 460));

        progressBar.setBackground(new java.awt.Color(204, 204, 204));
        progressBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 740, -1));

        loadingValue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(102, 102, 102));
        loadingValue.setText("0 %");
        jPanel1.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        loadingLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(102, 102, 102));
        loadingLabel.setText("Loading ...");
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loadingLabel;
    public javax.swing.JLabel loadingValue;
    public javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
