/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctors;

import Admin.AdminPanel;
import Doctors.connect;
import Login.loginPage;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GaXown
 */
public class addDoctor extends javax.swing.JFrame {
    DefaultTableModel deftmod = new DefaultTableModel();
    /**
     * Creates new form addDoctor
     */
    public addDoctor() {
        initComponents();
        Object columns[] = { "doctor_id", "doctor_name","doctor_departement","doctor_phone_number" };
        deftmod.setColumnIdentifiers(columns);
        DoctorsTable.setModel(deftmod);
        
        try {
            loadData();
        } catch (ClassNotFoundException ex) {
            System.out.println("load fct not working");
        }
    }
    
    public void loadData() throws ClassNotFoundException{
        try {
            Connection conn;
        
        deftmod.getDataVector().removeAllElements();
        deftmod.fireTableDataChanged();
        conn = connect.connectdb();
        String querry = "select * from doctor_info";
        Statement st = conn.createStatement();
        ResultSet rs=st.executeQuery(querry);
        Object columnData[] = new Object[8];
        while (rs.next()) {
            columnData[0] = rs.getString("id");
            columnData[1] = rs.getString("name");
            columnData[2] = rs.getString("gender");
            columnData[3] = rs.getString("address");
            columnData[4] = rs.getString("dept");
            columnData[5] = rs.getString("phone");
            columnData[6] = rs.getString("username");
            columnData[7] = rs.getString("password");
            deftmod.addRow(columnData);
            }
            conn.close();
            
        }catch(SQLException e){
            System.out.println("sql error");
        }
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        logOut_Btn2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        d_id = new textfield.TextField();
        d_password = new textfield.PasswordField();
        d_phone = new textfield.TextField();
        d_address = new textfield.TextField();
        d_name = new textfield.TextField();
        d_gender = new textfield.TextField();
        d_username = new textfield.TextField();
        d_dept = new textfield.TextField();
        jLabel2 = new javax.swing.JLabel();
        d_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DoctorsTable.setAutoCreateRowSorter(true);
        DoctorsTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DoctorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor_ID", "Doctor_Name", "Doctor_Specialization", "Doctor_phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DoctorsTable.setGridColor(new java.awt.Color(204, 204, 204));
        DoctorsTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(DoctorsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1050, 244));

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Add A Doctor__________ ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 38, -1, 65));

        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backs.png"))); // NOI18N
        back_btn.setText("jLabel2");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        jPanel2.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 50));

        logOut_Btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross.png"))); // NOI18N
        logOut_Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut_Btn2logOut_BtnMouseClicked(evt);
            }
        });
        jPanel2.add(logOut_Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d_id.setLabelText("ID");
        d_id.setName("ID"); // NOI18N
        jPanel3.add(d_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 170, -1));

        d_password.setLabelText("Password");
        jPanel3.add(d_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 170, -1));

        d_phone.setLabelText("Phone number");
        jPanel3.add(d_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 260, -1));

        d_address.setLabelText("Adress");
        jPanel3.add(d_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 260, -1));

        d_name.setLabelText("Full Name");
        jPanel3.add(d_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 170, -1));

        d_gender.setLabelText("Gender");
        jPanel3.add(d_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 260, -1));

        d_username.setLabelText("Username");
        jPanel3.add(d_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 170, -1));

        d_dept.setLabelText("Dept");
        jPanel3.add(d_dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 260, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Humaaans - 3 Characters.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, -10, 390, 230));

        d_add.setBackground(new java.awt.Color(255, 255, 255));
        d_add.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        d_add.setForeground(new java.awt.Color(108, 99, 255));
        d_add.setText("ADD");
        d_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 99, 255), 2, true));
        d_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_addActionPerformed(evt);
            }
        });
        jPanel3.add(d_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 240, 170, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1000, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
    new DoctorsCP().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    private void d_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_addActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String id = d_id.getText();
            String name = d_password.getText();
            String password = d_name.getText();
            String address = d_address.getText();
            String phone = d_phone.getText();
            String dept = d_dept.getText();
            String gender = d_gender.getText();
            String username = d_username.getText();
            
            Connection con = null;
            con = connect.connectdb();
            
            
            
            
            String querry = "insert into doctor_info values(?,?,?,?,?,?,?,?)";
            java.sql.PreparedStatement st = con.prepareStatement(querry);
            st.setString(1, id);
            st.setString(2, name);
            st.setString(3, gender);
            st.setString(4, address);
            st.setString(5, dept);
            st.setString(6, phone);
            st.setString(7, username);
            st.setString(8, password);
            int x = st.executeUpdate();
            loadData();
           
            JOptionPane.showMessageDialog(null, "Data Saved ("  + x + " row updated)");    
        } catch (ClassNotFoundException ex) {
            System.out.println("errorrrr");
        } catch (SQLException ex) {
            System.out.println("error2");
                 
        }
    }//GEN-LAST:event_d_addActionPerformed

    private void logOut_Btn2logOut_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut_Btn2logOut_BtnMouseClicked
        new loginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_Btn2logOut_BtnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DoctorsTable;
    private javax.swing.JLabel back_btn;
    private javax.swing.JButton d_add;
    private textfield.TextField d_address;
    private textfield.TextField d_dept;
    private textfield.TextField d_gender;
    private textfield.TextField d_id;
    private textfield.TextField d_name;
    private textfield.PasswordField d_password;
    private textfield.TextField d_phone;
    private textfield.TextField d_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOut_Btn2;
    // End of variables declaration//GEN-END:variables
}
