/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctors;

import Admin.AdminPanel;
import Login.loginPage;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GaXown
 */
public class delDoctor extends javax.swing.JFrame {
 DefaultTableModel deftmod = new DefaultTableModel();
    

    public delDoctor() {
        initComponents();
         Object columns[] = { "doctor_id", "doctor_name","doctor_departement","doctor_phone_number" };
        deftmod.setColumnIdentifiers(columns);
        DoctorsTable.setModel(deftmod);
        
        try {
            loadData();
        } catch (ClassNotFoundException ex) {
            System.out.println("load fct not working");
        } 
    }
    
    public void loadData() throws ClassNotFoundException{
        try {
            Connection con;
        
        deftmod.getDataVector().removeAllElements();
        deftmod.fireTableDataChanged();
        con = connect.connectdb();
        String querry = "select * from doctor_info";
        Statement st = con.createStatement();
        ResultSet rs=st.executeQuery(querry);
        Object columnData[] = new Object[4];
        while (rs.next()) {
            columnData[0] = rs.getString("id");
            columnData[1] = rs.getString("name");
            columnData[2] = rs.getString("dept");
            columnData[3] = rs.getString("phone");
            deftmod.addRow(columnData);
                    
            }
        }catch(SQLException e){
            System.out.println("sql error");
        }
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DoctorsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn1 = new javax.swing.JLabel();
        logOut_Btn2 = new javax.swing.JLabel();
        d_id = new textfield.TextField();
        d_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DoctorsTable.setAutoCreateRowSorter(true);
        DoctorsTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DoctorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor_ID", "Doctor_Name", "Doctor_Specialization", "Doctor_phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DoctorsTable.setGridColor(new java.awt.Color(204, 204, 204));
        DoctorsTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(DoctorsTable);

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("delete A Doctor account__________ ");

        back_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backs.png"))); // NOI18N
        back_btn1.setText("jLabel2");
        back_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btn1MouseClicked(evt);
            }
        });

        logOut_Btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross.png"))); // NOI18N
        logOut_Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOut_Btn2logOut_BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOut_Btn2)
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addGap(0, 105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logOut_Btn2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        d_id.setLabelText("ID");
        d_id.setName("ID"); // NOI18N

        d_delete.setBackground(new java.awt.Color(255, 255, 255));
        d_delete.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        d_delete.setForeground(new java.awt.Color(108, 99, 255));
        d_delete.setText("DELETE");
        d_delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 99, 255), 2, true));
        d_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        d_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(d_id, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(d_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(d_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(d_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btn1MouseClicked
new DoctorsCP().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btn1MouseClicked

    private void d_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_deleteActionPerformed
        // TODO add your handling code here:
        try {
         // TODO add your handling code here:
         String id = d_id.getText();
         //String name = d_name.getText();
         Connection con = null;
         con = connect.connectdb();
         String querry1="select id from doctor_info";
         java.sql.Statement s1 = con.createStatement();
         ResultSet rs1 = s1.executeQuery(querry1);
         boolean id_notfound=true;
         while(rs1.next()){
             if(id.equals(rs1.getString("id"))){
                 id_notfound=false;
                 break;
             }else{
                 id_notfound=true;
             }
         }
         if(id_notfound==false){
            String querry = "delete from doctor_info where id=?";
            java.sql.PreparedStatement st = con.prepareStatement(querry);
            st.setString(1, id);
            int x = st.executeUpdate();
            JOptionPane.showMessageDialog(null, "doctor removed ");
            loadData();
            con.close();
         }else{
             JOptionPane.showMessageDialog(null, "id not found!!!");
         }
         
         
         
       
         
     } catch (ClassNotFoundException ex) {
         System.out.println("class_error");
     } catch (SQLException ex) {
         System.out.println("sql_error");
     }
    }//GEN-LAST:event_d_deleteActionPerformed

    private void logOut_Btn2logOut_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOut_Btn2logOut_BtnMouseClicked
        new loginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_logOut_Btn2logOut_BtnMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DoctorsTable;
    private javax.swing.JLabel back_btn1;
    private javax.swing.JButton d_delete;
    private textfield.TextField d_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logOut_Btn2;
    // End of variables declaration//GEN-END:variables
}
