/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Doctors.DoctorPanel;
import Doctors.DoctorsCP;
import Login.loginPage;
import Patients.PatientsCP;
import Receptionist.Appointements;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author GaXown
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        DoctorSection = new javax.swing.JPanel();
        DoctorIco = new javax.swing.JLabel();
        DoctorsBtn = new javax.swing.JButton();
        PatientSection = new javax.swing.JPanel();
        PatientIco = new javax.swing.JLabel();
        PatientsBtn = new javax.swing.JButton();
        appointement_selection = new javax.swing.JPanel();
        appointements_label = new javax.swing.JLabel();
        appointements = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        DoctorSection.setBackground(new java.awt.Color(255, 255, 255));
        DoctorSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DoctorSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoctorSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoctorSectionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DoctorSectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoctorSectionMouseExited(evt);
            }
        });

        DoctorIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Doctors.png"))); // NOI18N

        DoctorsBtn.setBackground(new java.awt.Color(255, 255, 255));
        DoctorsBtn.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        DoctorsBtn.setForeground(new java.awt.Color(108, 99, 255));
        DoctorsBtn.setText("Doctors");
        DoctorsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 99, 255), 2, true));
        DoctorsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DoctorsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DoctorsBtnMouseExited(evt);
            }
        });
        DoctorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorSectionLayout = new javax.swing.GroupLayout(DoctorSection);
        DoctorSection.setLayout(DoctorSectionLayout);
        DoctorSectionLayout.setHorizontalGroup(
            DoctorSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DoctorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addComponent(DoctorIco, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );
        DoctorSectionLayout.setVerticalGroup(
            DoctorSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DoctorIco, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PatientSection.setBackground(new java.awt.Color(255, 255, 255));
        PatientSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PatientSection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PatientSection.setPreferredSize(new java.awt.Dimension(320, 70));
        PatientSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientSectionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PatientSectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PatientSectionMouseExited(evt);
            }
        });
        PatientSection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Injured.png"))); // NOI18N
        PatientSection.add(PatientIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 278));

        PatientsBtn.setBackground(new java.awt.Color(255, 255, 255));
        PatientsBtn.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        PatientsBtn.setForeground(new java.awt.Color(108, 99, 255));
        PatientsBtn.setText("Patients");
        PatientsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 99, 255), 2, true));
        PatientsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PatientSection.add(PatientsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 291, 216, 50));

        appointement_selection.setBackground(new java.awt.Color(255, 255, 255));
        appointement_selection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        appointement_selection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appointement_selection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointement_selectionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appointement_selectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appointement_selectionMouseExited(evt);
            }
        });

        appointements_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/MedicalCare.png"))); // NOI18N

        appointements.setBackground(new java.awt.Color(255, 255, 255));
        appointements.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        appointements.setForeground(new java.awt.Color(108, 99, 255));
        appointements.setText("Appointements");
        appointements.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(108, 99, 255), 2, true));
        appointements.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout appointement_selectionLayout = new javax.swing.GroupLayout(appointement_selection);
        appointement_selection.setLayout(appointement_selectionLayout);
        appointement_selectionLayout.setHorizontalGroup(
            appointement_selectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointement_selectionLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(appointements, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointement_selectionLayout.createSequentialGroup()
                .addComponent(appointements_label, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        appointement_selectionLayout.setVerticalGroup(
            appointement_selectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointement_selectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appointements_label, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointements, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(DoctorSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PatientSection, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(appointement_selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoctorSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appointement_selection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1060, 440));

        jPanel6.setBackground(new java.awt.Color(108, 99, 255));

        jLabel1.setBackground(new java.awt.Color(108, 99, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Panel ");

        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cross.png"))); // NOI18N
        home_btn.setText("jLabel3");
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap(469, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(home_btn)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setColor(JButton b) {
        b.setBackground(new Color(108,99,255));
        b.setForeground(new Color(255,255,255));
    } 
    
    private void resetColor(JButton b) {
        b.setForeground(new Color(108,99,255));
        b.setBackground(new Color(255,255,255));
    }
    
    private void DoctorSectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorSectionMouseEntered
        // TODO add your handling code here:
        setColor(DoctorsBtn);
    }//GEN-LAST:event_DoctorSectionMouseEntered

    private void DoctorSectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorSectionMouseExited
        // TODO add your handling code here:
        resetColor(DoctorsBtn);
    }//GEN-LAST:event_DoctorSectionMouseExited

    private void PatientSectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientSectionMouseEntered
        // TODO add your handling code here:
        setColor(PatientsBtn);
    }//GEN-LAST:event_PatientSectionMouseEntered

    private void PatientSectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientSectionMouseExited
        // TODO add your handling code here:
        resetColor(PatientsBtn);
    }//GEN-LAST:event_PatientSectionMouseExited

    private void appointement_selectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointement_selectionMouseEntered
        // TODO add your handling code here:
        setColor(appointements);
    }//GEN-LAST:event_appointement_selectionMouseEntered

    private void appointement_selectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointement_selectionMouseExited
        // TODO add your handling code here:
        resetColor(appointements);
    }//GEN-LAST:event_appointement_selectionMouseExited
    
    
    /* Navigation */
    
    
    private void DoctorSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorSectionMouseClicked
        // TODO add your handling code here:
        new DoctorsCP().setVisible(true);
        dispose();
    }//GEN-LAST:event_DoctorSectionMouseClicked

    private void appointement_selectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointement_selectionMouseClicked
        // TODO add your handling code here:
        new Appointements().setVisible(true);
        dispose();
    }//GEN-LAST:event_appointement_selectionMouseClicked

    private void PatientSectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientSectionMouseClicked
        // TODO add your handling code here:
        new PatientsCP().setVisible(true);
        dispose();
    }//GEN-LAST:event_PatientSectionMouseClicked

    private void home_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseClicked
        new loginPage().setVisible(true);
        dispose();
    }//GEN-LAST:event_home_btnMouseClicked

    private void DoctorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorsBtnActionPerformed

    /* Hover Effects */
    private void DoctorsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoctorsBtnMouseExited
        // TODO add your handling code here:
        resetColor(DoctorsBtn);
    }//GEN-LAST:event_DoctorsBtnMouseExited

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorIco;
    private javax.swing.JPanel DoctorSection;
    private javax.swing.JButton DoctorsBtn;
    private javax.swing.JLabel PatientIco;
    private javax.swing.JPanel PatientSection;
    private javax.swing.JButton PatientsBtn;
    private javax.swing.JPanel appointement_selection;
    private javax.swing.JButton appointements;
    private javax.swing.JLabel appointements_label;
    private javax.swing.JLabel home_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
